"""Compose and send the daily digest email via Gmail SMTP."""

from __future__ import annotations

import os
import smtplib
import ssl
from datetime import datetime
from email.message import EmailMessage
from html import escape


def _render_html(papers: list[dict]) -> str:
    date_str = datetime.now().strftime("%A, %B %d, %Y")

    if not papers:
        return f"""
<html><body style="font-family: -apple-system, system-ui, sans-serif; max-width: 680px; margin: 0 auto; padding: 24px; color: #222;">
  <h1 style="font-size: 22px; margin-bottom: 4px;">AI Hardware Digest</h1>
  <p style="color: #888; margin-top: 0;">{date_str}</p>
  <p>No relevant papers in the last 48 hours. arXiv is quiet today.</p>
</body></html>
"""

    cards = []
    for i, p in enumerate(papers, 1):
        authors = ", ".join(p["authors"][:3])
        if len(p["authors"]) > 3:
            authors += f", +{len(p['authors']) - 3} more"

        cards.append(f"""
<div style="border-left: 3px solid #4a6fa5; padding: 12px 16px; margin: 16px 0; background: #fafbfc;">
  <div style="font-size: 12px; color: #888; margin-bottom: 4px;">
    #{i} &middot; score {p["score"]}/10 &middot; <span style="font-family: monospace;">{escape(p["primary_category"])}</span>
  </div>
  <div style="font-size: 16px; font-weight: 600; margin-bottom: 6px;">
    <a href="{escape(p["url"])}" style="color: #1a1a1a; text-decoration: none;">{escape(p["title"])}</a>
  </div>
  <div style="font-size: 13px; color: #555; margin-bottom: 8px;">{escape(authors)}</div>
  <div style="font-size: 14px; color: #333; margin-bottom: 8px;"><em>{escape(p["summary"])}</em></div>
  <div style="font-size: 13px; color: #444;">{escape(p["abstract"][:280])}{"…" if len(p["abstract"]) > 280 else ""}</div>
  <div style="margin-top: 8px;">
    <a href="{escape(p["url"])}" style="font-size: 12px; color: #4a6fa5;">abs</a> &middot;
    <a href="{escape(p["url"].replace("/abs/", "/pdf/"))}" style="font-size: 12px; color: #4a6fa5;">pdf</a>
  </div>
</div>
""")

    return f"""
<html><body style="font-family: -apple-system, system-ui, sans-serif; max-width: 680px; margin: 0 auto; padding: 24px; color: #222;">
  <h1 style="font-size: 22px; margin-bottom: 4px;">AI Hardware Digest</h1>
  <p style="color: #888; margin-top: 0;">{date_str} &middot; {len(papers)} paper{"s" if len(papers) != 1 else ""}</p>
  {"".join(cards)}
  <p style="font-size: 11px; color: #aaa; margin-top: 24px;">Generated by ai-hardware-digest. Source: arXiv. Ranked by Claude.</p>
</body></html>
"""


def _render_text(papers: list[dict]) -> str:
    date_str = datetime.now().strftime("%A, %B %d, %Y")
    lines = [f"AI Hardware Digest — {date_str}", ""]
    if not papers:
        lines.append("No relevant papers in the last 48 hours.")
        return "\n".join(lines)
    for i, p in enumerate(papers, 1):
        lines.append(f"#{i} [{p['primary_category']}] score {p['score']}/10")
        lines.append(p["title"])
        lines.append(", ".join(p["authors"][:3]) + (f", +{len(p['authors'])-3} more" if len(p["authors"]) > 3 else ""))
        lines.append(p["summary"])
        lines.append(p["url"])
        lines.append("")
    return "\n".join(lines)


def send_digest(papers: list[dict]) -> None:
    sender = os.environ["GMAIL_ADDRESS"]
    password = os.environ["GMAIL_APP_PASSWORD"]
    recipient = os.environ.get("RECIPIENT_EMAIL", sender)

    msg = EmailMessage()
    msg["Subject"] = f"AI Hardware Digest — {datetime.now().strftime('%b %d')}"
    msg["From"] = sender
    msg["To"] = recipient
    msg.set_content(_render_text(papers))
    msg.add_alternative(_render_html(papers), subtype="html")

    ctx = ssl.create_default_context()
    with smtplib.SMTP_SSL("smtp.gmail.com", 465, context=ctx) as server:
        server.login(sender, password)
        server.send_message(msg)
    print(f"sent digest with {len(papers)} papers to {recipient}")
